openapi: 3.0.1
info:
  title: Gradle Demo
  description: ""
  version: 1.0.0
servers:
- url: http://localhost:8080/
paths:
  /greet:
    get:
      summary: Get a greeting
      operationId: greet
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
components:
  schemas:
    Greeting:
      type: object
      properties:
        greeting:
          type: string
          example: 'Hello!'
