/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.1).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.demo.gradle.api;

import com.demo.gradle.model.Greeting;
import io.swagger.annotations.*;
import java.util.Optional;
import javax.validation.constraints.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "greet", description = "the greet API")
public interface GreetApi {

  default Optional<NativeWebRequest> getRequest() {
    return Optional.empty();
  }

  /**
   * GET /greet : Get a greeting
   *
   * @return OK (status code 200)
   */
  @ApiOperation(
      value = "Get a greeting",
      nickname = "greet",
      notes = "",
      response = Greeting.class,
      tags = {})
  @ApiResponses(value = {@ApiResponse(code = 200, message = "OK", response = Greeting.class)})
  @GetMapping(
      value = "/greet",
      produces = {"application/json"})
  default ResponseEntity<Greeting> greet() {
    getRequest()
        .ifPresent(
            request -> {
              for (MediaType mediaType : MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                  String exampleString = "{ \"greeting\" : \"Hello!\" }";
                  ApiUtil.setExampleResponse(request, "application/json", exampleString);
                  break;
                }
              }
            });
    return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
  }
}
